### ISSUE TITLE
Ability to set line and fill opacity

### ISSUE THREAD

**Issue by PikaMug** [BlueMap-Minecraft/BlueMapAPI#2]
API methods such as `ShapeMarker#setLineOpacity` and `ShapeMarker#setFillOpacity` would be useful, especially for 3D shapes which might otherwise conceal structures or landmarks.

**Comment by TBlueF** [comment]
The `setLineColor` and `setFillColor` methods both accept a `Color` object which also has an alpha-value. You can use that to set the opacity :)
That's what you need, right? ^^

**Comment by PikaMug** [comment]
My conundrum is that I'm letting colors be user configurable by hex value, for which I use `Color#decode`. Yes, I could use `Color(float r, float g, float b, float a)` but having three separate config nodes for RGB besides the one for transparency doesn't strike me as user-friendly. I'm not sure how Dynmap manages to have separate methods for opacity, but I'll try looking into it once I get the chance.

**Comment by TBlueF** [comment]
It's not a problem to create separate methods for opacity, it just was a design choice not to do that. ^^

Hex-values can also include alpha values, e.g. `#FF000088`, or you could easily do the decoding yourself to have your config exactly like you want, and still use the available functions :)

**Comment by PikaMug** [comment]
True, but it  seems `Color#decode` doesn't  accept that format. I also tried `0xFF000088` and `FF000088`, but no dice. I could substring the hex value, but it seems `AARRGGBB` and `RRGGBBAA` are both common formats, so I'm not sure how to differentiate between the two if the end user goes with the "wrong" one.

**Comment by TBlueF** [comment]
```java
Color opaqueColor = Color.decode(yourColorConfigString);
int opacity = (int) (yourOpacityConfigValue * 255); //assuming your yourOpacityConfigValue is a float with range 0-1
Color combinedColor = new Color(
    opaqueColor.getRed(),
    opaqueColor.getGreen(),
    opaqueColor.getBlue(),
    opacity
);
marker.setBorderColor(combinedColor);
```
*(pseudocode, untested)*

That would be my suggestion. You have two separate configs for color and opacity like you wanted, but you can use the existing API-method :)

**Comment by PikaMug** [comment]
Back from a short trip, seems it I didn't occur to me that opacity could be translated into an int like that. Works great, thank you!
