### ISSUE TITLE
Cannot access BlueMapAPI with Bluemap

### ISSUE THREAD

**Issue by Rosstail** [BlueMap-Minecraft/BlueMapAPI#8]
Hi,

I am trying to make my spigot/paper plugin compatible with BlueMapAPI.

The thing is, using `BluemapAPI.getInstance().isPresent()` always returns false despite that the plugin being active on my server.
How can I fix this ?

BlueMapAPI version: 2.7.2
Server version: Spigot / Paper 1.21.X
BlueMap version: 5.4

**Comment by Chicken** [comment]
It may be that BlueMap isn't loaded yet at the time of calling that, make sure to use `BlueMapAPI.onEnable((api) -> { ... });`

**Comment by TechnicJelle** [comment]
Also, make sure you're not including BlueMap into your own plugin's JAR.
You need to mark it as "provided" (or equivalent term in the build system you're using)

**Comment by Rosstail** [comment]
> It may be that BlueMap isn't loaded yet at the time of calling that, make sure to use `BlueMapAPI.onEnable((api) -> { ... });`

Effectively, I did forgot to add `BlueMapAPI` and `BlueMap` to the list of the softdepends. It has fixed the problem. Thanks !

> Also, make sure you're not including BlueMap into your own plugin's JAR. You need to mark it as "provided" (or equivalent term in the build system you're using)

The dependency were marked as provided, yes. Hopefully, the problem did not come from here.

Thanks to both of you !

**Comment by TechnicJelle** [comment]
I'm glad you've solved your issue! 🥳

Though I do wonder if that was the actual solution...

Sometimes I, too, forget to add BlueMap to the (soft)depends of my new plugin(s), and it still usually works...
And when it does error, it's an actual error! Something like "unknown class BlueMapAPI".
It shouldn't just make `isPresent()` return false.

BTW, you shouldn't need to add "BlueMapAPI" to there. Just "BlueMap" should be enough. ([example](https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/blob/050a7f63eceb85ce1e8ae63e92cfd4d14427d106/src/main/resources/plugin.yml#L5))
